# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0968c3b4246d29a2b125cdda3613c3aae3e6229c41800a9db72e6811e31eced70d296c5b41c6c5f212f6d2cefee691d3543ce8a0e69f9b094c64e0c466341323

test:
  secret_key_base: 52478cb01eccd13855c121849385c90255e9df1ccbe64c0d42d218c5c0333c06c443467bee9f8fb405f650e960a5a7e712cc91c14084d524a392f11ceaffaa2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
